<template>
    <AppLayout>
        <Head title="Upload Document" />
        <div class="space-y-6 fade-up">
            <PageHeader
                title="Upload Document"
                kicker="Documents"
                subtitle="Submit new records with complete metadata for tracking and review."
            >
                <template #actions>
                    <Link href="/documents" class="soft-button-light">Back to List</Link>
                </template>
            </PageHeader>

            <!-- Validation errors banner (form-level only) -->
            <div
                v-if="Object.keys(form.errors).length > 0"
                class="flex items-start gap-3 border border-red-400 bg-red-50 px-4 py-3 text-sm font-medium text-red-800 mb-6"
            >
                <svg class="mt-0.5 h-4 w-4 shrink-0 text-red-500" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
                </svg>
                <div>
                    <p class="font-semibold">Please fix the following errors before submitting:</p>
                    <ul class="mt-1 list-disc list-inside space-y-0.5 text-xs">
                        <li v-for="(msg, field) in form.errors" :key="field">{{ msg }}</li>
                    </ul>
                </div>
            </div>

            <SectionCard
                title="Document Details"
                eyebrow="Submission"
                subtitle="Provide accurate information to streamline the review process."
            >
                <form class="grid gap-5 lg:grid-cols-2" @submit.prevent="submit" enctype="multipart/form-data">

                    <!-- Auto-generated Reference Number (read-only) -->
                    <div class="lg:col-span-2">
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1">
                            Reference Number
                            <span class="ml-2 text-[10px] font-normal normal-case text-gray-400">(Auto-generated by system)</span>
                        </label>
                        <div class="flex items-center gap-3">
                            <input
                                :value="refNumber"
                                readonly
                                class="soft-input bg-blue-50 text-[#003366] font-bold cursor-default w-48"
                            />
                            <span class="text-xs text-gray-400">This number is assigned automatically and cannot be changed.</span>
                        </div>
                    </div>

                    <!-- Title -->
                    <div>
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1" for="title">
                            Title <span class="text-red-500">*</span>
                        </label>
                        <input
                            id="title"
                            v-model="form.title"
                            class="soft-input"
                            placeholder="Document title"
                            required
                        />
                        <p v-if="form.errors.title" class="mt-1 text-xs text-red-600">{{ form.errors.title }}</p>
                    </div>

                    <!-- Category -->
                    <div>
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1" for="category">
                            Category
                        </label>
                        <select id="category" v-model="form.category_id" class="soft-select">
                            <option :value="null">— Select category —</option>
                            <option v-for="cat in categories" :key="cat.id" :value="cat.id">
                                {{ cat.name }}
                            </option>
                        </select>
                        <p v-if="form.errors.category_id" class="mt-1 text-xs text-red-600">{{ form.errors.category_id }}</p>
                    </div>

                    <!-- Priority -->
                    <div>
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1" for="priority">
                            Priority <span class="text-red-500">*</span>
                        </label>
                        <select id="priority" v-model="form.priority" class="soft-select" required>
                            <option value="Standard">Standard</option>
                            <option value="Priority">Priority</option>
                            <option value="Urgent">Urgent</option>
                        </select>
                        <p v-if="form.errors.priority" class="mt-1 text-xs text-red-600">{{ form.errors.priority }}</p>
                    </div>

                    <!-- File Retention / Life -->
                    <div>
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1" for="retention_days">
                            File Retention Period <span class="text-red-500">*</span>
                        </label>
                        <select id="retention_days" v-model="form.retention_days" class="soft-select" required>
                            <option
                                v-for="option in retentionOptions"
                                :key="option.value"
                                :value="option.value"
                            >
                                {{ option.label }}
                            </option>
                        </select>
                        <p class="mt-1 text-xs text-gray-400">
                            When this period ends, the document is automatically moved to the archive.
                        </p>
                        <p v-if="form.errors.retention_days" class="mt-1 text-xs text-red-600">{{ form.errors.retention_days }}</p>
                    </div>

                    <!-- Description -->
                    <div class="lg:col-span-2">
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1" for="description">
                            Description
                        </label>
                        <textarea
                            id="description"
                            v-model="form.description"
                            class="soft-input min-h-[120px] resize-y"
                            placeholder="Brief overview or special instructions"
                        ></textarea>
                        <p v-if="form.errors.description" class="mt-1 text-xs text-red-600">{{ form.errors.description }}</p>
                    </div>

                    <!-- File Upload -->
                    <div class="lg:col-span-2">
                        <label class="block text-xs font-bold uppercase tracking-widest text-gray-600 mb-1">
                            Attach File
                            <span class="ml-1 font-normal normal-case text-gray-400">(PDF, DOC, DOCX, JPG, PNG — max 10MB)</span>
                        </label>
                        <input
                            type="file"
                            accept=".pdf,.doc,.docx,.png,.jpg,.jpeg"
                            class="w-full border border-dashed border-gray-300 bg-gray-50 px-4 py-5 text-sm text-gray-600 file:mr-4 file:border-0 file:bg-[#003366] file:px-4 file:py-1.5 file:text-xs file:font-bold file:text-white file:cursor-pointer hover:border-[#003366] transition cursor-pointer"
                            @change="handleFile"
                        />
                        <p v-if="form.errors.file" class="mt-1 text-xs text-red-600">{{ form.errors.file }}</p>
                    </div>

                    <!-- Actions -->
                    <div class="lg:col-span-2 flex flex-col sm:flex-row gap-3 pt-2 border-t border-gray-200">
                        <button
                            type="submit"
                            class="soft-button w-full sm:w-auto disabled:opacity-60"
                            :disabled="form.processing"
                        >
                            {{ form.processing ? 'Submitting...' : 'Submit for Review' }}
                        </button>
                        <button
                            type="reset"
                            class="soft-button-light w-full sm:w-auto"
                            @click="form.reset()"
                            :disabled="form.processing"
                        >
                            Clear Form
                        </button>
                    </div>
                </form>
            </SectionCard>
        </div>
    </AppLayout>
</template>

<script setup>
import { Head, Link, useForm } from "@inertiajs/vue3";
import AppLayout from "../../Layouts/AppLayout.vue";
import PageHeader from "../../Components/PageHeader.vue";
import SectionCard from "../../Components/SectionCard.vue";

const props = defineProps({
    categories:       { type: Array, default: () => [] },
    refNumber:        { type: String, default: '' },
    retentionOptions: { type: Array, default: () => [] },
});

const form = useForm({
    title:          '',
    category_id:    null,
    priority:       'Standard',
    retention_days: 365,
    description:    '',
    file:           null,
});

const handleFile = (e) => {
    form.file = e.target.files[0] ?? null;
};

const submit = () => {
    form.post('/documents', {
        forceFormData: true,
    });
};
</script>
