import {
    Archive,
    Award,
    Building2,
    ClipboardCheck,
    FileText,
    GitBranch,
    Inbox,
    LayoutDashboard,
    RotateCcw,
    ScrollText,
    Settings,
    UserCheck,
    Users,
} from "@lucide/vue";

export const navIconMap = {
    LayoutDashboard,
    FileText,
    GitBranch,
    RotateCcw,
    UserCheck,
    Award,
    Archive,
    Users,
    Building2,
    ClipboardCheck,
    Inbox,
    ScrollText,
    Settings,
};

export const navIconByHref = {
    "/dashboard": "LayoutDashboard",
    "/documents": "FileText",
    "/documents/returned": "RotateCcw",
    "/workflow": "GitBranch",
    "/visitors": "UserCheck",
    "/certificates": "Award",
    "/archive": "Archive",
    "/users": "Users",
    "/departments": "Building2",
    "/approvals": "ClipboardCheck",
    "/requests": "Inbox",
    "/audit": "ScrollText",
    "/settings": "Settings",
};
